[workspace]
members = ["native", "lexer", "wasm"]
resolver = "2"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"

[profile.release.package.wasm]
# optimization for size (more aggressive)
opt-level = "z"
